name: Deploy to Ubuntu Server

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CORS_ORIGIN: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Build Docker images
        run: |
          docker build . -t wordhive:${{ github.sha }}

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: remove old container
        run: |
          docker rm --force wordhive

      - name: run new container
        run: |
          docker run -d --restart unless-stopped --name wordhive -p 4500:3000 wordhive:${{ github.sha }}
